name: ZotBox
version: 1.3.9.1
main: XZot1K.plugins.zb.ZotBox
description: An advanced bukkit/spigot library/utility plugin that can make a variety of things easier!
commands:
  zotbox:
    default: op
    aliases: [zotbox, zb]