name: ZotBox
version: 1.4
main: XZot1K.plugins.zb.ZotBox
description: An advanced bukkit/spigot library plugin crossover that can make a variety of things easier!
commands:
  zotbox:
    default: op
    aliases: [zotbox, zb]