name: ZotBox
version: 1.3.8.4
main: XZot1K.plugins.zb.ZotBox
description: An amazing bukkit/spigot library and utility plugin used by the legendary XZot1K!
commands:
  zotbox:
    default: op
    aliases: [zotbox, zb]